##################################################
## Project: all bats
## Script purpose: analysing the output of the array job 'bold_querying.R'
## Date: 06/06/18
## Author: Dave Hemprich-Bennett (hemprich.bennett@gmail.com)
## Notes
##################################################

library(here)
library(bold)
library(ggmap)


setwd(here())

files <- list.files(pattern = 'taxonomic_info*', path = 'data/')
files <- paste('data/', files, sep = '')
#One of these files is an old attempt at running a non-array job, one was the final one and returned empty
files <- files[-c(1,17)]
 
files <- lapply(files, read.csv)

alltax <- do.call(rbind, files)

pests <- scan('data/pest_species.txt', character(), sep = ',')
#remove empty values (generated by an error in my import command which I didn't get around to fixing yet)
pests <- pests[-which(pests=='')]

#These are potential pest MOTU consumed by bats
pestconsumption <- alltax[which(alltax$taxonomicidentification %in% pests),]


write.csv(pestconsumption, 'results/pestvals.csv')

#####Plot where the pests were collected####
midpoint <- c(lon=	117.321995, lat = 4.699939)
se_asia <- get_map(midpoint, source = 'google', maptype = 'roadmap', zoom = 4)

pests <- ggmap(se_asia) +
  geom_point(aes(x = specimen_lon, y = specimen_lat), col = 'orange', alpha = 0.2,
             data = pestconsumption)

pests


#####Now plot all matches####
all_midpoint <- c(lon=	18, lat = 4.699939)
world <- get_map(all_midpoint, source = 'google', maptype = 'hybrid', zoom = 1)

map <- ggmap(world) +
  geom_point(aes(x = specimen_lon, y = specimen_lat), col = 'orange', alpha = 0.2,
             data = alltax)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "white"), axis.ticks.y=element_blank(), axis.text.y=element_blank())+
  labs(x = NULL, y= NULL)
map  
pdf('plots/worldwide_bold_matches.pdf')
map
dev.off()




#Extract the bestmatches
best <- as.character(pestconsumption[which(pestconsumption$similarity > 0.97),'X'])
names(best) <- as.character(pestconsumption[which(pestconsumption$similarity > 0.97),'taxonomicidentification'])
best <- gsub('\\..+', '', best)



source('scripts/r/r_network_gen.r')


nets <- r_network_gen(collapse_species = T, filter_species = T, lulu = T, include_malua = F)
names(nets) <- gsub('DANUM', 'Danum', names(nets))
names(nets) <- gsub('MALIAU', 'Maliau', names(nets))


mat <- matrix(nrow = 0, ncol = length(nets)+2) 
for(i in 1:length(best)){
  vec <- c(best[i], names(best)[i],sapply(nets, function(x) best[i] %in% rownames(x)))
  mat <- rbind(mat, vec)
  rownames(mat)[i] <- best[i]
}

df <- as.data.frame(mat)

