##################################################
## Project: all bats
## Script purpose: analysing the output of the array job 'bold_querying.R'
## Date: 06/06/18
## Author: Dave Hemprich-Bennett (hemprich.bennett@gmail.com)
## Notes
##################################################

library(here)
library(bold)

setwd(here())

files <- list.files(pattern = 'taxonomic_info*', path = 'data/')
files <- paste('data/', files, sep = '')
#One of these files is an old attempt at running a non-array job, one was the final one and returned empty
files <- files[-c(1,17)]
 
files <- lapply(files, read.csv)

alltax <- do.call(rbind, files)

pests <- scan('data/pest_species.txt', character(), sep = ',')
#remove empty values (generated by an error in my import command which I didn't get around to fixing yet)
pests <- pests[-which(pests=='')]

#These are potential pest MOTU consumed by bats
pestconsumption <- alltax[which(alltax$taxonomicidentification %in% pests),]


write.csv(pestconsumption, 'results/pestvals.csv')
