if(interactive()==TRUE){
  library('here')
  library(ggplot2)
  library(tidyverse)
  library(ggridges)
  library(gridExtra)
  library(forcats)
  library(reshape2)
  #library(multcompView)
}else{
  library(here, lib.loc = '/data/home/btw863/r_packages/')
}

setwd(here())
source('scripts/r/r_network_gen.r')

field_data <- read.csv(here('data/Edited_all_files_with_lat_long_VKedits.csv'))
field_data$SiteAndYear <- paste(field_data$Site, field_data$Year, sep = ', ')
field_data$Faeces_no1 <- gsub('T', '', field_data$Faeces_no1)
field_data$Faeces_no2 <- gsub('T', '', field_data$Faeces_no2)

all_interactions <- r_network_gen(collapse_species = F, desired_species = 'Hice', include_malua = T)
#all_interactions <- r_network_gen(collapse_species = F)
###Something is wrong with the data generated by all_interactions atm, the first column is empty

prey_data <- read.csv('data/taxonomy/order.csv')
colnames(prey_data) <- c('MOTU', 'Taxa')
prey_data$MOTU <- as.character(prey_data$MOTU)

# prey_data <- data.frame(rownames(all_interactions)[2:nrow(all_interactions)], sample(c('Lepidoptera','Diptera','Coleoptera'), nrow(all_interactions)-1, replace = T))


###Add the taxonomic information to the interactions for everything
taxa_mat <- all_interactions[1,]
z <- 2
for(i in 1: nrow(all_interactions)){
  rowname = rownames(all_interactions)[i]
  if(!rowname %in% prey_data$MOTU){
    next()
  }
  tax = as.character(prey_data[which(prey_data$MOTU == rowname),'Taxa'])
  if(is.null(nrow(taxa_mat))){ #If its the first iteration there won't be any rownames yet, so the next if statement will fail
    taxa_mat <- rbind(taxa_mat, all_interactions[i,])
    rownames(taxa_mat)[z] <- tax
    z <- z+1
  }
  if(tax %in% rownames(taxa_mat)){
    to_merge = which(rownames(taxa_mat)==tax)
    taxa_mat[to_merge,] <- taxa_mat[to_merge,]+ all_interactions[i,]
  }else{
    taxa_mat <- rbind(taxa_mat, all_interactions[i,])
    rownames(taxa_mat)[z] <- tax
    z <- z+1
  }
}
#The colnames currently have the sample numbers, we want them to be a useable value in the data frame
colnames(taxa_mat) <- taxa_mat[1,]
taxa_mat <- taxa_mat[-1,]

#####Make a list with a network for each site####

nets <- list()
sites <- unique(colnames(all_interactions))




for(i in 1:length(sites)){
  m =  all_interactions[,which(colnames(all_interactions )==sites[i])]
  colnames(m) = m[1,]
  m = m[-1,]
  nets[[i]] <- m
}
print(sites)
names(nets) <- sites


igraph_list <- list()

for(n in 1:length(nets)){
  net <- nets[[n]]
  molten_net <- melt(net)
  molten_net_2 <- molten_net[(which(molten_net[,3] != 0)),]
  bat_igraph <- graph.data.frame(molten_net_2, directed = F)
  V(bat_igraph)$type <- V(bat_igraph)$name %in% molten_net_2[,1]
  
  igraph_list[[n]] <- bat_igraph
  
  #Make colours vector
  node_cul <- rep("yellow", length(V(bat_igraph)))
  for(i in 1: length(V(bat_igraph))){
    if(length(grep('denovo',V(bat_igraph)[[i]]$name))>0){ #If the node is an OTU
      node_cul[i] <- "#01c2cd"
    }
  }
  pdf(paste('plots/Hice/networks/', names(nets)[n], '.pdf', sep =''))
  plot(bat_igraph, vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[n])
  dev.off()
}

par(mfrow= c(2,3))


pdf('plots/Hice/networks/all_nets.pdf')
par(mfrow= c(3,3))
plot(igraph_list[[5]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[5])
plot(igraph_list[[8]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[8])
plot(igraph_list[[2]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[2])
plot(igraph_list[[6]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[6])
plot(igraph_list[[1]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[1])
plot(igraph_list[[3]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[3])
plot(igraph_list[[7]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[7])
plot(igraph_list[[4]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[4])
dev.off()

png('plots/Hice/networks/all_nets.png')
par(mfrow= c(3,3))
plot(igraph_list[[5]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[5])
plot(igraph_list[[8]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[8])
plot(igraph_list[[2]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[2])
plot(igraph_list[[6]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[6])
plot(igraph_list[[1]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[1])
plot(igraph_list[[3]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[3])
plot(igraph_list[[7]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[7])
plot(igraph_list[[4]], vertex.size = 10, vertex.color=node_cul, vertex.label=NA, main = names(nets)[4])
dev.off()
